let dados = [
    {
      titulo: "Pilates",
      descricao: "Ideal para quem busca um corpo mais forte, flexível e alinhado. Os movimentos precisos e controlados do Pilates trabalham todos os músculos, melhoram a postura e ainda ajudam a relaxar a mente. É como um abraço para o seu corpo!",
      link: "https://pt.wikipedia.org/wiki/Pilates/",
      porcentagemdecaloriasquepodemsergastas : "",
      alimentaçãorecomendada : "",
      locaisondepraticar : "",
      intensidade : "",
      beneficios : "",
      musculostrabalhados : "",
      precaucoes : "",
    },
    {
      titulo: "Treinamento Funcional",
      descricao: "O treinamento funcional trabalha o corpo como um todo, utilizando movimentos naturais do dia a dia. Fortalece os músculos, melhora a coordenação e o equilíbrio, preparando o corpo para as atividades do cotidiano.",
      link: "https://pt.wikipedia.org/wiki/Treinamento_funcional",
      porcentagemdecaloriasquepodemsergastas : "",
      alimentaçãorecomendada : "",
      locaisondepraticar : "",
      intensidade : "",
      beneficios : "",
      musculostrabalhados : "",
      precaucoes : "",
    },
    {
      titulo: "Musculação",
      descricao: "A musculação é ideal para quem busca aumentar a força e a massa muscular. Através de exercícios com pesos, é possível definir os músculos e melhorar a performance física.",
      link: "https://pt.wikipedia.org/wiki/Muscula%C3%A7%C3%A3o",
      porcentagemdecaloriasquepodemsergastas : "",
      alimentaçãorecomendada : "",
      locaisondepraticar : "",
      intensidade : "",
      beneficios : "",
      musculostrabalhados : "",
      precaucoes : "",
    },
    {
        titulo: "Aeróbico (Corrida na Esteira)",
        descricao: "Uma atividade cardiovascular que melhora a resistência, queima calorias e tonifica os músculos das pernas. Ideal para quem busca perder peso e melhorar a saúde do coração.",
        link: "https://pt.wikipedia.org/wiki/Corrida",
        porcentagemdecaloriasquepodemsergastas: "Moderada a alta, dependendo da intensidade e duração.",
        alimentaçãorecomendada: "Rica em carboidratos complexos para fornecer energia e proteínas para a recuperação muscular.",
        locaisondepraticar: "Academias, residências com esteira, parques (corrida ao ar livre).",
        intensidade: "Variável, desde caminhadas leves até corridas de alta intensidade.",
        beneficios: "Melhora a saúde cardiovascular, fortalece os músculos das pernas, auxilia na perda de peso, reduz o estresse, aumenta a resistência.",
        musculostrabalhados: "Quadríceps, panturrilhas, glúteos, core.",
        precaucoes: "Consultar um médico antes de iniciar, usar calçados adequados, prestar atenção aos sinais do corpo e evitar o overtraining."
    },
    {
        titulo: "Crossfit",
        descricao: "Um programa de treinamento de alta intensidade que combina exercícios variados, funcionais e constantemente variados. Desenvolve força, resistência, flexibilidade e agilidade.",
        link: "https://www.crossfit.com/",
        porcentagemdecaloriasquepodemsergastas: "Muito alta, devido à alta intensidade e variedade de exercícios.",
        alimentaçãorecomendada: "Equilibrada, com foco em macronutrientes (carboidratos, proteínas e gorduras) e micronutrientes, para atender às altas demandas energéticas dos treinos.",
        locaisondepraticar: "Boxes de crossfit (academias especializadas).",
        intensidade: "Muito alta, com exercícios que exigem força, resistência e explosão.",
        beneficios: "Melhora a capacidade física geral, aumenta a força, desenvolve a resistência cardiovascular, melhora a coordenação motora, aumenta a densidade mineral óssea.",
        musculostrabalhados: "Corpo inteiro, com foco em grandes grupos musculares e core.",
        precaucoes: "Exige acompanhamento profissional para evitar lesões, iniciar gradualmente, respeitar os limites do corpo."
    },
  ];